title:            CTFdev
longtitle:        CTF tips and tricks for organizers, developers and content creators
author:           Pantelis Roditis
email:            proditis@echothrust.com
description: >
  Tip & Tricks for CTF organizers, developers and content creators.

version:          1.0
gitbook_version:  3.2.3

url:              'https://proditis.github.io'
baseurl:          '/CTFdev'
rss:              RSS
favicon_path:     /assets/gitbook/images/favicon.ico
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

remote_theme: sighingnow/jekyll-gitbook
syntax_highlighter_style: colorful
markdown_ext:     markdown,mkdown,mkdn,mkd,md

toc:
    enabled: true
    h_min: 1
    h_max: 3

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
