# Docs: https://github.com/marketplace/actions/markdown-link-check

name: Markdown links checker

on:
  # Trigger the workflow on push or pull requests, but only for the
  # main branch
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
#      with:
#        use-quiet-mode: 'yes'
#        config-file: 'mlc_config.json'
